steps:
  #build the docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_AR_HOSTNAME/$_PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME', 'myapp/']

  # PUSH THE DOCKER IMAGE TO ARTIFACT REGISTRY
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_AR_HOSTNAME/$_PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME']

  # DEPLOY THE IMAGE TO CLOUD RUN
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - $_SERVICE_NAME
      - '--image'
      - '$_AR_HOSTNAME/$_PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME'
      - '--platform'
      - 'managed'
      - '--region'
      - $_DEPLOY_REGION
      - '--allow-unauthenticated'



timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY